preload = /home/lilwassie/Downloads/doug-bagg-Ksxl4EjRvuY-unsplash.jpg
wallpaper = eDP-1,/home/lilwassie/Downloads/doug-bagg-Ksxl4EjRvuY-unsplash.jpg
wallpaper = HDMI-A-2,/home/lilwassie/Downloads/doug-bagg-Ksxl4EjRvuY-unsplash.jpg
fit_mode = cover
