preload = /home/lilwassie/Downloads/jeremy-thomas-E0AHdsENmDg-unsplash.jpg

wallpaper {
    monitor = eDP-1
    path = /home/lilwassie/Downloads/jeremy-thomas-E0AHdsENmDg-unsplash.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/lilwassie/Downloads/jeremy-thomas-E0AHdsENmDg-unsplash.jpg
    fit_mode = cover
}
