preload = /home/lilwassie/Downloads/jeremy-thomas-E0AHdsENmDg-unsplash.jpg
wallpaper = eDP-1,/home/lilwassie/Downloads/jeremy-thomas-E0AHdsENmDg-unsplash.jpg
wallpaper = HDMI-A-2,/home/lilwassie/Downloads/jeremy-thomas-E0AHdsENmDg-unsplash.jpg
fit_mode = cover
